# Generated by Django 2.0.13 on 2020-03-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='skill',
            field=models.CharField(default='addition', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
