# Generated by Django 2.0.13 on 2020-03-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouni', '0002_auto_20200305_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
