# Generated by Django 2.0.13 on 2020-03-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouni', '0005_auto_20200305_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='skillType',
        ),
    ]
