# Generated by Django 2.0.13 on 2020-03-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouni', '0010_auto_20200307_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.CharField(max_length=20),
        ),
    ]
