# Generated by Django 2.0.13 on 2020-03-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouni', '0011_auto_20200307_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
