# Generated by Django 2.0.13 on 2020-03-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mouni', '0012_auto_20200307_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='student',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultperexam',
            name='que_pick_ans',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.CharField(max_length=20),
        ),
    ]
