# Generated by Django 2.0.13 on 2020-03-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouni', '0014_resultperexam_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultperexam',
            name='remarks',
            field=models.TextField(default='good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultperexam',
            name='total_marks',
            field=models.PositiveIntegerField(default=10, editable=False),
            preserve_default=False,
        ),
    ]
