# Generated by Django 2.0.13 on 2020-03-18 12:17

from django.db import migrations, models
import mouni.models


class Migration(migrations.Migration):

    dependencies = [
        ('mouni', '0016_auto_20200314_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='skillType',
            field=models.CharField(help_text='skill you wanna test students in this exam', max_length=20, validators=[mouni.models.validate_fields]),
        ),
    ]
